-- Generated by `drizzle-kit generate`, with one hand edit: the three tables rebuilt below each gain
-- a column in the same migration that widens another one (SQLite cannot ALTER a column, so drizzle
-- recreates the whole table). Drizzle's INSERT ... SELECT listed the brand-new column as if the old
-- table already had it, which fails to apply; those three entries read NULL instead. Everything
-- else is verbatim generator output — regenerate it from src/db/schema.ts rather than editing it.

CREATE TABLE `application_secrets` (
	`id` text PRIMARY KEY NOT NULL,
	`application_id` text NOT NULL,
	`secret_hash` text NOT NULL,
	`hint` text NOT NULL,
	`label` text,
	`expires_at` integer,
	`last_used_at` integer,
	`revoked_at` integer,
	`created_by` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`created_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `application_secrets_hash_unique` ON `application_secrets` (`secret_hash`);--> statement-breakpoint
CREATE INDEX `application_secrets_application_id_idx` ON `application_secrets` (`application_id`);--> statement-breakpoint
CREATE TABLE `authorization_requests` (
	`id` text PRIMARY KEY NOT NULL,
	`handle_hash` text NOT NULL,
	`application_id` text NOT NULL,
	`redirect_uri` text NOT NULL,
	`state` text,
	`nonce` text,
	`code_challenge` text,
	`code_challenge_method` text,
	`scope` text,
	`prompt` text,
	`login_hint` text,
	`expires_at` integer NOT NULL,
	`request_ip` text,
	`user_agent` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `authorization_requests_handle_unique` ON `authorization_requests` (`handle_hash`);--> statement-breakpoint
PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_authorization_codes` (
	`id` text PRIMARY KEY NOT NULL,
	`code_hash` text NOT NULL,
	`user_id` text NOT NULL,
	`application_id` text NOT NULL,
	`provider` text NOT NULL,
	`redirect_uri` text NOT NULL,
	`nonce` text,
	`code_challenge` text,
	`code_challenge_method` text,
	`scope` text,
	`expires_at` integer NOT NULL,
	`consumed_at` integer,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `__new_authorization_codes`("id", "code_hash", "user_id", "application_id", "provider", "redirect_uri", "nonce", "code_challenge", "code_challenge_method", "scope", "expires_at", "consumed_at", "created_at") SELECT "id", "code_hash", "user_id", "application_id", "provider", "redirect_uri", NULL, "code_challenge", "code_challenge_method", "scope", "expires_at", "consumed_at", "created_at" FROM `authorization_codes`;--> statement-breakpoint
DROP TABLE `authorization_codes`;--> statement-breakpoint
ALTER TABLE `__new_authorization_codes` RENAME TO `authorization_codes`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `authorization_codes_hash_unique` ON `authorization_codes` (`code_hash`);--> statement-breakpoint
CREATE TABLE `__new_magic_link_tokens` (
	`id` text PRIMARY KEY NOT NULL,
	`email` text NOT NULL,
	`user_id` text,
	`application_id` text NOT NULL,
	`token_hash` text NOT NULL,
	`redirect_uri` text NOT NULL,
	`state` text,
	`nonce` text,
	`code_challenge` text,
	`code_challenge_method` text,
	`scope` text,
	`expires_at` integer NOT NULL,
	`consumed_at` integer,
	`request_ip` text,
	`user_agent` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `__new_magic_link_tokens`("id", "email", "user_id", "application_id", "token_hash", "redirect_uri", "state", "nonce", "code_challenge", "code_challenge_method", "scope", "expires_at", "consumed_at", "request_ip", "user_agent", "created_at") SELECT "id", "email", "user_id", "application_id", "token_hash", "redirect_uri", "state", NULL, "code_challenge", "code_challenge_method", "scope", "expires_at", "consumed_at", "request_ip", "user_agent", "created_at" FROM `magic_link_tokens`;--> statement-breakpoint
DROP TABLE `magic_link_tokens`;--> statement-breakpoint
ALTER TABLE `__new_magic_link_tokens` RENAME TO `magic_link_tokens`;--> statement-breakpoint
CREATE UNIQUE INDEX `magic_link_tokens_hash_unique` ON `magic_link_tokens` (`token_hash`);--> statement-breakpoint
CREATE INDEX `magic_link_tokens_email_created_idx` ON `magic_link_tokens` (`email`,`created_at`);--> statement-breakpoint
CREATE TABLE `__new_oauth_states` (
	`id` text PRIMARY KEY NOT NULL,
	`provider` text NOT NULL,
	`state_hash` text NOT NULL,
	`application_id` text NOT NULL,
	`redirect_uri` text NOT NULL,
	`client_state` text,
	`client_nonce` text,
	`code_challenge` text,
	`code_challenge_method` text,
	`scope` text,
	`provider_code_verifier` text NOT NULL,
	`nonce` text NOT NULL,
	`expires_at` integer NOT NULL,
	`consumed_at` integer,
	`request_ip` text,
	`user_agent` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
INSERT INTO `__new_oauth_states`("id", "provider", "state_hash", "application_id", "redirect_uri", "client_state", "client_nonce", "code_challenge", "code_challenge_method", "scope", "provider_code_verifier", "nonce", "expires_at", "consumed_at", "request_ip", "user_agent", "created_at") SELECT "id", "provider", "state_hash", "application_id", "redirect_uri", "client_state", NULL, "code_challenge", "code_challenge_method", "scope", "provider_code_verifier", "nonce", "expires_at", "consumed_at", "request_ip", "user_agent", "created_at" FROM `oauth_states`;--> statement-breakpoint
DROP TABLE `oauth_states`;--> statement-breakpoint
ALTER TABLE `__new_oauth_states` RENAME TO `oauth_states`;--> statement-breakpoint
CREATE UNIQUE INDEX `oauth_states_hash_unique` ON `oauth_states` (`state_hash`);--> statement-breakpoint
ALTER TABLE `applications` ADD `token_endpoint_auth_method` text DEFAULT 'none' NOT NULL;--> statement-breakpoint
ALTER TABLE `applications` ADD `post_logout_redirect_uris` text DEFAULT '[]' NOT NULL;--> statement-breakpoint
ALTER TABLE `applications` ADD `grant_types` text DEFAULT '["authorization_code","refresh_token"]' NOT NULL;--> statement-breakpoint
ALTER TABLE `applications` ADD `scopes` text DEFAULT '[]' NOT NULL;--> statement-breakpoint
ALTER TABLE `applications` ADD `require_pkce` integer DEFAULT true NOT NULL;--> statement-breakpoint
ALTER TABLE `applications` ADD `allowed_origins` text DEFAULT '[]' NOT NULL;