-- Generated by `drizzle-kit generate` and renumbered by hand from 0005 to 0007, past the
-- hand-written 0005/0006, which the journal does not list (see this app's CLAUDE.md); the journal's
-- last entry carries the matching `idx`/`tag` so the next generation is named 0008. The DDL itself
-- is verbatim generator output.
--
-- `country` and `city` record where Cloudflare placed a sign-in, so "close everything outside the
-- places I know" can be asked of `POST /me/sessions/prune`. Both stay null on every row written
-- before this migration, and the prune rules read a null as "unknown", never as a mismatch — an
-- older session is not closed for having no location.

ALTER TABLE `sessions` ADD `country` text;--> statement-breakpoint
ALTER TABLE `sessions` ADD `city` text;
