-- Hand-written, not generated by drizzle-kit: it creates the avatar moderation table and seeds the
-- two permissions that guard its administration routes, which a schema diff cannot know about.
--
-- The permissions are attached to the `admin` global role the same way `0001_seed.sql` does it, so
-- an existing administrator can review uploads without a grant being made by hand after the deploy.

CREATE TABLE IF NOT EXISTS `avatar_uploads` (
  `id` text PRIMARY KEY NOT NULL,
  `user_id` text NOT NULL,
  `object_key` text,
  `content_type` text NOT NULL,
  `size` integer NOT NULL,
  `status` text DEFAULT 'pending' NOT NULL,
  `reviewed_by` text,
  `reviewed_at` integer,
  `review_note` text,
  `created_at` integer DEFAULT (unixepoch()) NOT NULL,
  `updated_at` integer DEFAULT (unixepoch()) NOT NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade,
  FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `avatar_uploads_user_id_idx` ON `avatar_uploads` (`user_id`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `avatar_uploads_status_created_idx` ON `avatar_uploads` (`status`,`created_at`);
--> statement-breakpoint
INSERT OR IGNORE INTO `permissions` (`id`, `slug`, `name`, `description`) VALUES
  ('3f1d9bd1-0a3d-4f2c-9a1e-4a4f6f0f3a11', 'avatars:read', 'Read avatar uploads', 'List the avatars users have uploaded and their review state'),
  ('9c4a7f52-6b18-4f0a-8b2d-51c9d0b7e622', 'avatars:review', 'Review avatar uploads', 'Approve or reject an uploaded avatar, and take a published one down');
--> statement-breakpoint
INSERT OR IGNORE INTO `role_permissions` (`role_id`, `permission_id`)
  SELECT `roles`.`id`, `permissions`.`id`
  FROM `roles`, `permissions`
  WHERE `roles`.`slug` = 'admin'
    AND `roles`.`application_id` IS NULL
    AND `permissions`.`slug` IN ('avatars:read', 'avatars:review');
