-- Generated by `drizzle-kit generate` and renumbered by hand from 0008 to 0009, past the
-- hand-written 0008, which the journal does not list (see this app's CLAUDE.md); the journal's last
-- entry carries the matching `idx`/`tag` so the next generation is named 0010. The generator also
-- re-emitted `CREATE TABLE avatar_uploads`, because the snapshot it diffs against had never seen
-- that hand-written table; those three statements were deleted, and the snapshot this migration
-- ships with now records it, so the next generation will not emit them again.
--
-- `sso_sessions` is the browser's session with this server: what lets a returning user authorize an
-- application instead of signing in again. `auth_time` rides from the authorization code onto the
-- session so the id_token keeps describing the sign-in rather than the exchange, and
-- `authorization_requests.sso_session_id` is how a parked request tells the sign-in front-end which
-- account the browser is already signed in as. All three are nullable: every row written before
-- this migration predates SSO, and every reader falls back to the pre-SSO behaviour on a null.

CREATE TABLE `sso_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`token_hash` text NOT NULL,
	`provider` text NOT NULL,
	`authenticated_at` integer NOT NULL,
	`last_seen_at` integer DEFAULT (unixepoch()) NOT NULL,
	`expires_at` integer NOT NULL,
	`revoked_at` integer,
	`revoked_reason` text,
	`ip` text,
	`user_agent` text,
	`country` text,
	`city` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `sso_sessions_token_unique` ON `sso_sessions` (`token_hash`);--> statement-breakpoint
CREATE INDEX `sso_sessions_user_id_idx` ON `sso_sessions` (`user_id`);--> statement-breakpoint
ALTER TABLE `authorization_codes` ADD `auth_time` integer;--> statement-breakpoint
ALTER TABLE `authorization_requests` ADD `sso_session_id` text REFERENCES sso_sessions(id);--> statement-breakpoint
ALTER TABLE `sessions` ADD `auth_time` integer;