-- Hand-written, not generated by drizzle-kit: it creates the settings table, seeds the one setting
-- this Worker reads today, and seeds the two permissions that guard its administration routes —
-- neither of which a schema diff can know about. It is therefore absent from `meta/_journal.json`,
-- like every other hand-written migration here.
--
-- `settings` is a key/value table rather than a one-row table with a column per setting, because a
-- setting is operational state rather than schema: adding one must not be a migration on a database
-- that a deploy races (see the root CLAUDE.md on why writes, not reads, are what a lagging schema
-- breaks here). Values are stored as text and parsed by `src/services/settings.ts`, which owns the
-- catalog, the types and the defaults — an unknown key in this table means nothing to the Worker.
--
-- `registration_open` seeds to `false`, which is exactly the behaviour this Worker had before this
-- migration existed: sign-up is invitation-only until an administrator opens it. A deploy that
-- applies this migration therefore changes nothing until somebody ticks the box.
--
-- The permissions are attached to the `admin` global role the same way `0001_seed.sql` and
-- `0008_avatar_uploads.sql` do it, so an existing administrator can open and close registration
-- without a grant being made by hand after the deploy.

CREATE TABLE IF NOT EXISTS `settings` (
  `key` text PRIMARY KEY NOT NULL,
  `value` text NOT NULL,
  `updated_by` text,
  `updated_at` integer DEFAULT (unixepoch()) NOT NULL,
  FOREIGN KEY (`updated_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
INSERT OR IGNORE INTO `settings` (`key`, `value`) VALUES
  ('registration_open', 'false');
--> statement-breakpoint
INSERT OR IGNORE INTO `permissions` (`id`, `slug`, `name`, `description`) VALUES
  ('3d2a0592-4839-4107-b521-c3b30efc3059', 'settings:read', 'Read settings', 'Read the authentication settings, including whether sign-up is open'),
  ('4b9f481e-24c4-4856-bd6a-f076beed5bf0', 'settings:write', 'Write settings', 'Open or close user registration and change the other authentication settings');
--> statement-breakpoint
INSERT OR IGNORE INTO `role_permissions` (`role_id`, `permission_id`)
  SELECT `roles`.`id`, `permissions`.`id`
  FROM `roles`, `permissions`
  WHERE `roles`.`slug` = 'admin'
    AND `roles`.`application_id` IS NULL
    AND `permissions`.`slug` IN ('settings:read', 'settings:write');
